AWSTemplateFormatVersion: "2010-09-09"
Description: cloudFormation RDS
Resources:
#---------------------------------------------------#
#Subnet                                             #
#---------------------------------------------------#
  MyRDSSubnet:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudFormation-RDS-DB-Subnet
      DBSubnetGroupName: CFN-RDS-Subnet
      SubnetIds:
      - !ImportValue PrivateSubnet1-ID
      - !ImportValue PrivateSubnet2-ID
      Tags:
      -
        Key: "Name"
        Value: MyRDSSubnet

#---------------------------------------------------#
#RDSinstance                                        #
#---------------------------------------------------#
  MyRDS:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: CloudFormationRDS
      DBInstanceClass: "db.t3.micro"
      Engine: "mysql"
      EngineVersion: "8.0.35"
      MasterUsername: "admin"
      MasterUserPassword: "Nb19900514"
      DBName: "cfnrds"
      BackupRetentionPeriod: 0
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: "gp2"
      AllocatedStorage: 20
      DeleteAutomatedBackups: false
      DBSubnetGroupName: !Ref MyRDSSubnet
      VPCSecurityGroups:
      - !ImportValue RDSSecurityGroup-ID
      Tags:
      -
        Key: Name
        Value: MyRDS
